language: java
install: true

dist: trusty
jdk: openjdk8

before_script:
  - chmod +x gradlew
script:
  - gradle build --scan -s
  - gradle codeCoverageRepor
after_success:
  - bash <(curl -s https://codecov.io/bash)
